### ISSUE TITLE
Difference to homebridge-camera-ffmpeg

### ISSUE THREAD

**Issue by sohnkarlsruhe** [Samfox2/homebridge-videodoorbell#1]
Where is the difference?

**Comment by Samfox2** [comment]
Itˋs a videodoorbell not just a camera.

**Comment by sohnkarlsruhe** [comment]
thanks

**Comment by sohnkarlsruhe** [comment]
now it works, but i see no difference to camera-ffmpeg

**Comment by Samfox2** [comment]
The difference is that you can trigger a doorbell event with a simple curl request:
curl -X POST -d 'ding=dong&dong=ding' http://IP:PORT 
or by just opening the site in your browser: 
http://IP:PORT

**Comment by sohnkarlsruhe** [comment]
That is the same notification like to push the Ring Button with the homebridge doorbird Plugin with a motion sensor

**Comment by Samfox2** [comment]
No, the notification says doorbell rang not motion detected.

**Comment by sohnkarlsruhe** [comment]
Ok, thats right, trank you very much for your help and your code!
