### ISSUE TITLE
What should the config.json file look like?

### ISSUE THREAD

**Issue by t6cmh** [Samfox2/homebridge-videodoorbell#10]
I am new to this.  What should the config.json file look like with both ffmpeg and videodoorbell plugins installed?

**Comment by Samfox2** [comment]
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
      	"source": "-re -i rtsp://myfancy_rtsp_stream",
        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30
      }
    }
  ]
},
{
  "platform": "Video-doorbell",
  "cameras": [
    {
      "name": "Camera Name",
      "videoConfig": {
      	"source": "-re -i rtsp://myfancy_rtsp_stream",
        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30,
      	"port": 5005    
      }
    }
  ]
}

**Comment by t6cmh** [comment]
Thank you, I will try that.  I am running a raspberry pi 3 with jessie.  Would you suggest I use ffmpeg or ffmpeg-omx?  Is this an either-or decision or does the -omx plugin run alongside the regular ffmpeg plugin?  Depending on the answer to this question, how does this change what I need to do to the config.json file and/or the other .js files?  Thank you for your help.

**Comment by Samfox2** [comment]
omx uses grafix card for calculation (which means higher frame rates). So I would uses this. It runs alongside with the regular ffmpeg plugin. The number of parallel streams running at you grafix card depends on the memory, you have to try this with your config.

**Comment by t6cmh** [comment]
Thanks.  Sorry for the trouble, but what would the config.json file looks like with all three plugins running?  Would I need to edit any of the index.js files?

**Comment by Samfox2** [comment]
I am sure you found a solution 😀
