### ISSUE TITLE
Trigger using GPIO pins

### ISSUE THREAD

**Issue by woinkeyman** [Samfox2/homebridge-videodoorbell#11]
Hi there! Works brilliantly, thanks! Currently test-triggering it using the browser on my phone, but any chance that we can trigger the doorbell using the GPIO pins? Can install my pi next to the actual (dumb) doorbell.

Thanks in adv for your help! :)

**Comment by Samfox2** [comment]
You can run your "gpio-interrupt-detection" in a separate script and trigger a curl command from there.

**Comment by woinkeyman** [comment]
Yup - managed to get a python script running on boot. Thanks for your help!
