### ISSUE TITLE
Door rings twice

### ISSUE THREAD

**Issue by DanielWeeber** [Samfox2/homebridge-videodoorbell#18]
Hey,

wonderful plugin, using it for multiple weeks now.

On (only) one device I have the problem that the door notification pops up twice and takes way longer to show up, about 10 seconds longer.

Any idea how to fix this?

Greets

**Comment by Samfox2** [comment]
You could try to define and modify the _throttle_ option in your config.json. This could suppress the double messages.

**Comment by DanielWeeber** [comment]
Hm, but it’s only on one device..

**Comment by Samfox2** [comment]
This shouldˋnt be a problem as the first ring would go through immediately. Otherwise, maybe an icloud sign out (and in) could help.

**Comment by DanielWeeber** [comment]
While it was working once after signout/signin to iCloud, it does now happen again twice. I know it's not a problem with your plugin, but I just wanted to ask if you have any idea.

**Comment by Samfox2** [comment]
Sorry, I have no idea why your phone rings twice.
