### ISSUE TITLE
Does not group with LockMechanismAccessory

### ISSUE THREAD

**Issue by speedyuy** [Samfox2/homebridge-videodoorbell#19]
Hi,
I have a RPi running Homebridge and a LockMechanismAccessory that controls my front door.
I created a new room with a VideoDoorbell Camera and added the LockMechanismAccessory.
The camera works great! I can see live video and I can trigger the notification using the URL and using the virtual button.
The problem is that I don't get a screenshot with the notification and the lock button doesn't show either.
What am I doing wrong?
Thank you!

**Comment by Samfox2** [comment]
Strange, I know a few users who successfully use it with a lock accessory. Which LockMechanismAccessory are you using?

**Comment by speedyuy** [comment]
I found the problem. I had an error with the stillImageSource, it needed user/pass.
Without this the grouping does not work.
Thanks!
