### ISSUE TITLE
FFmpeg exited with code 1

### ISSUE THREAD

**Issue by postelnikov** [Samfox2/homebridge-videodoorbell#24]
Hi! can not start streaming. I get this mistake: FFmpeg exited with code 1
just regular cameras on other plugins seem to work.

**Comment by paqpaqpaq** [comment]
same here.

Runs just fine on every other plugin with ffmpeg, but just not on this plugin.
Therefor the plugin doesn;' function at all (?)

**Comment by paqpaqpaq** [comment]
Tested the plugin on a different Homebridge setup, with a different camera.
Same issue.
No snapshot, no stream. Same error.

The camera on that setup works just fine in the ffmpeg omx plugin too.

**Comment by paqpaqpaq** [comment]
I got both of mine to work now.
It is really in how the stream URL is presented, despite it works just fin in another plugin.

one accepts &channel=1&stream=0./
this plugin wants &channel=1&stream=0.sdp?

**Comment by Samfox2** [comment]
Nice to hear that it is working now.
