### ISSUE TITLE
motion sensor works also ?

### ISSUE THREAD

**Issue by roe1974** [Samfox2/homebridge-videodoorbell#27]
When i put an additional motion sensor in the same room .... will i get snapshots when motion is recognized ? ... or only when Ring button is pressed ?

Richard

**Comment by Samfox2** [comment]
Motion sensor should also work.

**Comment by roe1974** [comment]
And the button in Homekit can be a http switch plugin ? .. or comes the ring button with your plugin ?
Richard

**Comment by Samfox2** [comment]
Both, you can trigger it manually by a http switch plugin or with the button that comes with the plugin. Homekit itself can also trigger it with a motion sensor.

**Comment by roe1974** [comment]
can the button that comes with your plugin be triggered from external (http) ?

**Comment by roe1974** [comment]
ahhhh found it in the readme ;-)
curl -X POST -d 'ding=dong&dong=ding' http://IP_OF_HOMEBRIDGE_RUNNING_DEVICE:PORT_DEFINED_IN_CONFIG
