### ISSUE TITLE
no pic when ring ... possible ?

### ISSUE THREAD

**Issue by roe1974** [Samfox2/homebridge-videodoorbell#29]
is it possible to get only „it has rang“ message without pic ?
i get the pic with the motion sensor that is in the same room ....

**Comment by Samfox2** [comment]
Nope, that was the intention of the „video“ doorbell plugin 😀

**Comment by roe1974** [comment]
OK ;-)
i have also the ffmpeg-camera plugin installed .. is that a problem ?
you gave also a ffmpeg.js .....

Richard

**Comment by jwheeler91** [comment]
Hmmm, I sometimes get a notification without a pic...

**Comment by Samfox2** [comment]
That could be caused by a bad network connection of your ios device or your cam, never happened with my setup.

**Comment by jwheeler91** [comment]
ok. thanks.
