### ISSUE TITLE
Intercom or Action trigger

### ISSUE THREAD

**Issue by danbridgellc** [Samfox2/homebridge-videodoorbell#3]
First great plugin - have it setup and working fine.  Any idea if it possible to have full intercom functionality work?  Also is it possible to trigger an action on rich notification - i.e. open gate?

**Comment by Samfox2** [comment]
Audio is still not working but triggering with your gate should work. You just have to bring it to start a script or use the ifttt plugin.

**Comment by danbridgellc** [comment]
Understood on the audio

regarding the action - I was looking for a UI button in the iOS notification that I could trigger an action with based on who it is at the gate, etc.  So I was assuming it would require some type of additional HomeKit code to know the door bell supports such a feature.  Any ideas/suggestions to get such a button in the notification?

**Comment by Samfox2** [comment]
I think the only things that you could change within the notification are volume/brightness and mute.

**Comment by danbridgellc** [comment]
been digging and actually believe it or not - it is much simpler than all that...all you have to do is add a "lock" service accessory into the same room as the doorbell and the rich notification includes a "Unlock Door" action button.  I am guessing that to get an intercom option, you would need a microphone and speaker service accessory - but I have not proved that piece yet.

**Comment by Samfox2** [comment]
Good to know. You can activate both speaker and microphone service in the index file of this plugin - just uncomment it. It‘s in but I couldn‘t get the audio stuff working with ffmpeg...

**Comment by Samfox2** [comment]
Audio is now implemented.

**Comment by chip131001** [comment]
I have activated the service speaker. Is it possible to trigger something with Mute?
I want to change a data point in iobroker when I press mute.
