### ISSUE TITLE
Grandstream GDS3710

### ISSUE THREAD

**Issue by unaxboy** [Samfox2/homebridge-videodoorbell#31]
Hello everyone!

Does someone try this plugin with [Grandstream GDS3710](http://www.grandstream.com/support/resources/?title=GDS3710)? How to config it?

@Samfox2 your help wanted)

**Comment by random9133** [comment]
Hi

I got it to work here. On the GDS3710 you need to enable Event Notification (Server: <homebridge_server_ip>:50005). As all events get through unfiltered, HomeKit reacts to all events. To make this more usable it would probably make sense to filter the traffic somehow.

This is my config.json:
`        {
            "platform": "Video-doorbell",
            "cameras": [
                {
                    "name": "My GDS3710",
                    "button": true,
                    "throttle": 3000,
                    "port": 50005,
                    "videoConfig": {
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:password@gds3710ip:554/0",
                        "source": "-re -i rtsp://ADMIN:ADMINPW@GDS3710IP:554/8",
                        "maxStreams": 2,
                        "maxWidth": 352,
                        "maxHeight": 240,
                        "maxFPS": 30,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": true
                    }
                }
            ]
        }
`

With Cmd4 I am also able to unlock the door via HomeKit.
As mentioned in the GDS3710 manual, this is a security risk as this is using an HTTP API call (you need to 'Enable HTTP API Remote Open Door' for it to work). The communication from Cmd4 to GDS3710 is done as described in http://www.grandstream.com/sites/default/files/Resources/gds37xx_http_api.pdf via the encrypted challenge/response mode.

Here is the config.json:
`        {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": true,
            "accessories": [
                {
                    "type": "LockMechanism",
                    "displayName": "My_LockMechanism",
                    "lockCurrentState": "UNSECURED",
                    "lockTargetState": "UNSECURED",
                    "name": "My_LockMechanism",
                    "stateChangeResponseTime": 3,
                    "state_cmd": "/YOURFOLDER/.homebridge/Cmd4Scripts/MyLock.js"
                }
            ]
        }
`

This command needs to go into MyLock.js (based on https://github.com/ztalbot2000/homebridge-cmd4/blob/master/Extras/Cmd4Scripts/PS4.sh):
`
...
         # ps4-waker
         curl -k `GDS=\`curl -sk "https://GDS3710IP/goform/apicmd?cmd=0&user=admin"\`&&md5 -s "\`echo $GDS|sed -e 's/.*<ChallengeCode>//g'|sed -e 's/<.ChallengeCode.*//g'\`:LOCALDOORUNLOCKPIN:ADMINPW"|sed -e "s/.* = /https:\/\/GDS3710IP\/goform\/apicmd\?cmd=1\&user=admin\&authcode=/g"|sed -e "s/$/\&idcode=\`echo $GDS|sed -e "s/.*<IDCode>//g"|sed -e "s/<.IDCode.*//g"\`\&type=1/g"`
         echo $4 > /tmp/fileVariableHolder
	/bin/sleep 2
	echo 1 > /tmp/fileVariableHolder
         exit $?
      else
...`

**Comment by Samfox2** [comment]
Nice.
