### ISSUE TITLE
Doorbell Notification and Lock Mechanism not combined while in same Room

### ISSUE THREAD

**Issue by x23piracy** [Samfox2/homebridge-videodoorbell#35]
Hi,

as i can see in your plugin description you write:

"If the same (HomeKit) room containing this camera also has a Lock mechanism accessory, the notification will show a working UNLOCK button. HomeKit/iOS will link them together automatically when they are in the same room."

I have added the following plugin to have a lock mechanism accessory (the camera and the lock mechanism and also the optional doorbell trigger button are all in the same room (default room)

https://www.npmjs.com/package/homebridge-http-lock-mechanism

Unfortunately when i trigger the notification there is no unlock button in the notification i may could use. Any idea why it's not working?

Btw. Why is a lock mechanism accessory working like On / Off, i use a Sonoff Relay with Pulsetime to trigger a door opener this is only activated once and deactivated automatically after x seconds by Sonoff's Pulsetime Option. Is there also a lock mechanism for just triggering something where the combination of the notification works?

Regards X23

**Comment by x23piracy** [comment]
I close the issue, i was just to stupid.
I don't knew how to open the notification :)

**Comment by Samfox2** [comment]
No problem, great to hear that it is working for you now.
