### ISSUE TITLE
No thumbnails.

### ISSUE THREAD

**Issue by Fernyman79** [Samfox2/homebridge-videodoorbell#39]
I only get a thumb alongside the notification about 50% of the time. When the notification doesn't contain the thumb, tapping on it won't launch home.app into the doorbell camera. It lunches the app in the home tab instead. Any thoughts on how to solve this?

**Comment by fabvis** [comment]
me too...

**Comment by Samfox2** [comment]
The plugin itself runs quite stable. Please make sure that all your devices are updated to the same iOS version and that your network connection is ok.

**Comment by Fernyman79** [comment]
I can’t trace a relationship between the client devices and the occurrence of this bug. On my case, I have iOS devices on 13 beta, as well as 12.4.1, and macOS devices on both Catalina and Mojave, and each receive a different notification.  

Regarding network, the RPi running homebridge is hard wired, and so are the macs. 

Any other tips on how I can troubleshoot this?

**Comment by Samfox2** [comment]
There are always issues with iOS beta versions and homekit. Especially in 13 grouping of accessories and icloud video recording are introduced (and tested in beta), those are major changes in homekit and unfortunately cause a lot of (syncing) problems. Let‘s hope that 13.1 will be more stable.

**Comment by fabvis** [comment]
> I can’t trace a relationship between the client devices and the occurrence of this bug. On my case, I have iOS devices on 13 beta, as well as 12.4.1, and macOS devices on both Catalina and Mojave. Sill, independent of the OS version, the snapshot doesn’t consistently appears.
> 
> Regarding network, the RPi running homebridge is hard wired, and so are the macs.
> 
> Any other tips on how I can troubleshoot this?

the same for me...
but, if i put a static image in stillimagesource, all notifications contains a thumb on all my devices (iOS 13.1 and 12.4.1 | macOS Mojave and Catalina)

**Comment by Fernyman79** [comment]
I wonder if it has anything to do with [https://github.com/KhaosT/HAP-NodeJS/pull/704](url)

**Comment by cuellarfr** [comment]
Same problem here, no thumbnails in notifications (iOS 13). I think it's related to this same issue they just solved in the homebridge-camera-ffmpeg plugin https://github.com/KhaosT/homebridge-camera-ffmpeg/commit/282fca44f5e219080633c878e201490d912aab75

**Comment by Samfox2** [comment]
That‘s only the case for motion sensors, in iOS 13 they have to be part of the cam itself, not separate accessories. Rich notifications (with snapshots) are working fine for others - including me. I‘m still trying to find the issue... Could you try to add your cam as a new doorbell with a different name?

**Comment by cuellarfr** [comment]
Well, that worked! I renamed the name of the camera in config, deleted the
camera from the home app, added the new one and the notifications started
working again (with pictures). Thanks!

**Comment by Samfox2** [comment]
Nice.
