### ISSUE TITLE
Publish at NPM

### ISSUE THREAD

**Issue by msuMax** [Samfox2/homebridge-videodoorbell#4]
Hi @Samfox2,

Just wanted to know if you are planning to publish this plugin at npm?

**Comment by Samfox2** [comment]
Yes, Im trying to do it around Christmas :-)

**Comment by msuMax** [comment]
Awesome! 

I look forward to trying it out.

**Comment by msuMax** [comment]
Hey @Samfox2, any news?:)
I am still excited to try it out, however by using docker+synology installing packages manually is not that easy :-(

**Comment by Samfox2** [comment]
Ok, published at npm.
Install this plugin using: npm install -g homebridge-videodoorbell
