### ISSUE TITLE
Usage of VideoFilters (-vf)

### ISSUE THREAD

**Issue by Zigzag968** [Samfox2/homebridge-videodoorbell#41]
Hi!

First, thanks for this plugin, it is really helpful!

I saw that this plugin is made from `homebridge-camera-ffmpeg` which the readme talk about a key `videoFilter` to put in the config file that can be used to override the `-vf scale=1280:720` put in the ffmpeg command. I did it in my config file but the key seems to be ignored as I still have the default `-vf`, is it normal? how can i use video filters? I also need to use `hflip` and `vflip` but it is ignored too.

Thanks a lot!

**Comment by Samfox2** [comment]
Those keys came later, so they are not (yet) supported by this plugin. I see if I can add them soon.
