### ISSUE TITLE
Notification delay

### ISSUE THREAD

**Issue by uspino2** [Samfox2/homebridge-videodoorbell#45]
The plugin works great. I'm triggering a notification with this http call:

`http://10.10.12.241:5005
`
The notification takes between 2 to 3 seconds to show up. With the Doorbird plug-in (which I think is based in the same code) the notification is pretty much instant. Is there something I might be doing wrong? Thanks!

**Comment by Samfox2** [comment]
Strange. Is it the same with the trigger button?

**Comment by uspino2** [comment]
Little faster with the button, but things have improved after a full Hombridge restart. Still not quite as instant as Doorbird plugin though. Should the http call have ant headers in it?

**Comment by Samfox2** [comment]
Http call does not need a header. The switch triggers instantly, a faster reactian is not possible (from homekit site).  Do you use still image source? Generating the pic could cause the slowdown.

**Comment by uspino2** [comment]
It might be two different things. The Doorbird is in local LAN and the Video Doorbell using your plug is in a different LAN. Also, Doorbird jpg is 640x480 and my other doorbell only serves 1280x720 jpg. I'll run some tests when I'm at the same LAN and let you know. But it does not seem related to your plugin, which works great.

**Comment by Samfox2** [comment]
Yes, if you reduce the resolution the image would also be ready much faster.

**Comment by uspino2** [comment]
That was correct: delay was due to snapshot resolution + out of lan connection. Thanks!

**Comment by Samfox2** [comment]
No problem.
