### ISSUE TITLE
http call for motion event

### ISSUE THREAD

**Issue by uspino2** [Samfox2/homebridge-videodoorbell#46]
The standard http call triggers a doorbell event (with live video). Motion events provide a snapshot instead of live video.  Is there a different http call to trigger a motion notification?

**Comment by Samfox2** [comment]
No, at this time there is no http call for motion. However, you can trigger the motion switch by an automation.

**Comment by uspino2** [comment]
Yes, and that works great, but I wanted to trigger it from a Shelly device.
Thanks anyway, great job!

**Comment by uspino2** [comment]
Just in case someone wonders, here’s why: if you setup a motion trigger automation when the door opens, Homekit sends you the snapshot but stops sending open/close notifications from that door sensor. So if you setup a motion trigger automation to see who opens the door, you’ll get the snapshot, but you’ll never know if the door has been properly closed.
