### ISSUE TITLE
Cannot get notification to fire

### ISSUE THREAD

**Issue by BenWoodford** [Samfox2/homebridge-videodoorbell#5]
I'm posting to the port and it HTTP 200s all fine and well, but I don't appear to be getting any notifications from it on my phone.

Should the doorbell only show as a single device (a camera) or should there be a second device for the actual doorbell and the camera is a secondary accessory?

**Comment by Samfox2** [comment]
Hi. It should appear as a single device. If it‘s not working please try another port, maybe it‘s already in use.

**Comment by BenWoodford** [comment]
The port is fine, I can see the web server output. Just don’t get any notifications when I trigger it for some reason

**Comment by BenWoodford** [comment]
It's worth mentioning that I don't have a notifications option on the camera that is exposed by this. For motion sensors there's a notifications setting on the accessory that I need to set. That isn't present here.

Could that be related? I don't have a homekit-compatible doorbell to use as a control test.

**Comment by Samfox2** [comment]
No, that‘s ok. Have you tried to sign out and sign in to your icloud account?

**Comment by BenWoodford** [comment]
I'll give it a go. I'll try running homebridge in debug mode too, maybe it'll give some info on what's going wrong.

**Comment by BenWoodford** [comment]
Nope, nothing. Unless perhaps my homebridge install is out of date...

Nope. Updated and still doesn't notify.

**Comment by Samfox2** [comment]
hmm, what does debug output say?

**Comment by BenWoodford** [comment]
Not much, just shows the "Ding dong!" message

**Comment by Samfox2** [comment]
#8 Maybe this solves your problem too...

**Comment by BenWoodford** [comment]
Oh the camera portion works, it's the notification portion that doesn't.

**Comment by Samfox2** [comment]
Maybe this helps

https://github.com/KhaosT/homebridge-amazondash/issues/28#event-1423958881

**Comment by BenWoodford** [comment]
I've already tried all of that unfortunately. Deleting it, restarting, update, etc. Nothing seems to stick.

Are you running the latest iOS version?

**Comment by Samfox2** [comment]
Yes

**Comment by BenWoodford** [comment]
A thought: could it be the RTSP stream I’m using isn’t liked by HomeKit?

**Comment by Samfox2** [comment]
If you can see a picture/stream at the camera in your home app this should not csuse any issues.

**Comment by Samfox2** [comment]
Could you try the updated version? Does at least the button trigger work?

**Comment by BenWoodford** [comment]
Nope, updated homebridge and the plugin, nothing has changed. I still just have one camera device, no other buttons anywhere.

Going to update my phone as it’s a few minor versions out.

Could you take some screenshots of what everything is meant to look like?

**Comment by normen** [comment]
I don‘t think the issue is with this plugin. Make sure you didn‘t disable messages for the Home app on your Phone.

**Comment by BenWoodford** [comment]
Ahah, seems to be working now! Not sure what change fixed it, but it’s working via button and URL. :)

**Comment by normen** [comment]
As said probably something on your side, none of the changes could have affected this in any way.

**Comment by Samfox2** [comment]
Great, working after months... :-) Closing this issue now - finally.
