### ISSUE TITLE
Add mapaudio and mapvideo parameters 

### ISSUE THREAD

**Issue by macjl** [Samfox2/homebridge-videodoorbell#51]
Hello,

Is it possible to add the mapaudio and mapvideo parameters as it’s done in homebridge-camera-ffmpeg?

I have a camera that provides 2 separated streams, and that’s why audio is not on 0.1, but on 1.0. With the mapaudio parameter, I was able to make it work in homebridge-camera-ffmpeg, but not with that plugin.

Thank you.

**Comment by Samfox2** [comment]
Sure - but I‘m not at home for the next 2 weeks, sorry. Should not be that difficult to locate and copy the code lines from homebridge-camera-ffmpeg plugin into this repo ;-)

**Comment by Samfox2** [comment]
Merged in dccda23 - thanks!
