### ISSUE TITLE
no snapshot since http motion sensor update ....

### ISSUE THREAD

**Issue by roe1974** [Samfox2/homebridge-videodoorbell#57]
hi
i have video-doorbell and http-motion-sensor in the same room ....
since update from today (http-motion-sensor) i have no more snapshots .... video works..
Other room with http sensor and ffmpeg-camera works without problems .....
thx for help, richard

**Comment by Samfox2** [comment]
should work after removing and re-adding the cam from your homekit setup.

**Comment by roe1974** [comment]
can i just do this ... or do i have to change name of the cam when i am removing and re-adding the same cam ?

**Comment by Samfox2** [comment]
Should work if you 1st remove the cam from your config.json, restart hombridge (then the cam is removed from homekit), re-add it with the same name and restart homebridge again. The final step would be to add it to homekit within home app.

**Comment by roe1974** [comment]
strange ..... snapshots is working @ home (LAN) ... but not outside (ATV as central) ... hmmmmmmm

**Comment by roe1974** [comment]
ok ... restart of internet modem + ATV solved the problem .... richard
