### ISSUE TITLE
Rich Notification

### ISSUE THREAD

**Issue by QDUNI** [Samfox2/homebridge-videodoorbell#60]
Hi, Great job so far works like a charm.

The only problem I have is that the notification is not always showing the rich notification with force press. This brings you to the live feed in the notification. It depends sometimes it works sometimes it doesn't. 

Any ideas how to fix this?
Motion does work with a snapshot always. but live feed is much nicer

**Comment by Samfox2** [comment]
Sorry no idea. Itˋs working for my setup without any issues. Maybe a problem with a bad connection?

**Comment by QDUNI** [comment]
What version of iOS do you use ?

**Comment by QDUNI** [comment]
When I launched the camera and go live. The notification will work with live feed. If I close the connection and trigger a notification I will get a notification but without livestream. You sure this isn't in the plugin? That you need some kind of delay to first start the stream before receiving a push notification?

**Comment by Samfox2** [comment]
I am on the latest iOS. I tried it and it works in my case on my iphone and my ipad as well. What cam are you using?

**Comment by QDUNI** [comment]
A foscam ip camera

**Comment by philhar88** [comment]
I am also seeing this issue.

iOS 13.4.1

Config:
```
        {
            "name": "Video Doorbell",
            "cameras": [
                {
                    "name": "Test Camera",
                    "port": 5005,
                    "button": true,
                    "motion": true,
                    "throttle": 1000,
                    "videoConfig": {
                        "source": "-re -i /dev/video0",
                        "maxStreams": 1,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "maxBitrate": 1200,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "vflip": false,
                        "hflip": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Video-doorbell"
        }
```

If I trigger the doorbell via this command:
`curl -d 'ding=dong&dong=ding' http://homebridge:5005/`

while the camera is streaming
```
[03/05/2020, 12:49:25 am] [Video Doorbell] Start streaming video from Test Camera with 1280x720@299kBit
ffmpeg -re -i /dev/video0 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 13947219 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params HkpKFkch87fZnEQLevzOjpGwL795BV8+Cx7dkHdd srtp://192.168.0.52:65167?rtcpport=65167&localrtcpport=65167&pkt_size=1316
Ding Dong!
```

I get the rich notification with the ability to see accessories in the same Room.

If I trigger the same command while camera not streaming, I only get the basic notification with no force press options.

**Comment by Samfox2** [comment]
So your hardware or network connection seems to be to slow. Homekit expects an answer in a certain time (not sure how much millisec., I have to look again). Think foscam do also offer a low res stream, maybe this is fast enough?

**Comment by QDUNI** [comment]
Got some issues with my iDevices. When I updated them all to 13.4.1 the plugin works perfectly without any issue. Thnx !
