### ISSUE TITLE
Issue with Homebridge 1.0.3

### ISSUE THREAD

**Issue by siobhanellis** [Samfox2/homebridge-videodoorbell#61]
I get the following error with Homebridge 1.0.3

One of your plugins incorrectly registered an external accessory using the platform name (Video-doorbell) and not the plugin identifier. Please report this to the developer!

**Comment by Samfox2** [comment]
Thanks for the report. I change it in the next release.

**Comment by Samfox2** [comment]
Fixed in c16516b
