### ISSUE TITLE
Hombridge crashing on macOs

### ISSUE THREAD

**Issue by pilotns** [Samfox2/homebridge-videodoorbell#64]
I have a completely fresh install of homebridge + homebridge-videodoorbell. Homblidge is crash when I add config: 

            "name": "Video Doorbell",
            "cameras": [
                {
                    "name": "Домофон",
                    "button": false,
                    "motion": false,
                    "throttle": 10000,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:admin@192.168.88.110:554/cam/realmonitor?channel=1&subtype=0",
                        "stillImageSource": "-i http://admin:admin@192.168.88.110/cgi-bin/snapshot.cgi?channel=1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "vflip": false,
                        "hflip": false,
                        "debug": false
                    },
                    "manufacturer": "Dahua",
                    "model": "VTO2101E-P-S1",
                    "serialNumber": "5H02E10PAZ4F85A",
                    "firmwareRevision": "4.300.0000000.3.R"
                }
            ],
            "platform": "Video-doorbell"

Crash log:

> TypeError: self.log is not a function
>     at videodoorbellPlatform.identify (/usr/local/lib/node_modules/homebridge-videodoorbell/index.js:52:10)
>     at PlatformAccessory.emit (events.js:315:20)
>     at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
>     at Accessory.emit (events.js:315:20)
>     at Accessory.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at Accessory._this._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:256:12)
>     at Identify.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:245:16)
>     at Identify.emit (events.js:315:20)
>     at Identify.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at Identify.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)

However if I install a homebridge-camera-ffmpeg plugin all is working fine with same links to stream.

**Comment by Samfox2** [comment]
Should be fixed in the new version, thanks.
