### ISSUE TITLE
No button or motion event/trigger installing

### ISSUE THREAD

**Issue by scottsimon1979** [Samfox2/homebridge-videodoorbell#75]
Heya - I've managed to get the plugin working and it does install the camera I specified as a Doorbell within Homekit.  But even though I've enabled the motion and button parameters - they dont seem to get installed with the doorbell.  Am I doing something wrong?  As it is right now, its reallyt just another camera until I can get those parameters working.

Thanks, and here is my config:

[
    {
        "name": "Front Door",
        "port": 5005,
        "videoConfig": {
            "source": "-re -i http://192.168.1.***/img/video.mjpeg",
            "stillImageSource": "-i http://192.168.1.***/img/snapshot.cgi?size=3",
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "button": true,
            "motion": true,
            "throttle": 4000
        }
    }
]

**Comment by toshibochan** [comment]
In the exemple have button and motion add this 2

{
  "platform": "Video-doorbell",
  "cameras": [
    {
      "name": "Camera Name",
      "port": 5005,
      "button": true,
      "motion": true,
      "throttle": 3000,
      "manufacturer": "ACME, Inc.",
      "model": "ABC-123",
      "serialNumber": "1234567890",
      "firmwareRevision": "1.0",
      "videoConfig": {
      	"source": "-re -i rtsp://myfancy_rtsp_stream",
      	"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30,
      	"vcodec": "h264_omx",
      	"audio": true,
      	"packetSize": 188,
      	"debug": true
      }
    }
  ]
}

**Comment by scottsimon1979** [comment]
> In the exemple have button and motion add this 2
> 
> {
> "platform": "Video-doorbell",
> "cameras": [
> {
> "name": "Camera Name",
> "port": 5005,
> "button": true,
> "motion": true,
> "throttle": 3000,
> "manufacturer": "ACME, Inc.",
> "model": "ABC-123",
> "serialNumber": "1234567890",
> "firmwareRevision": "1.0",
> "videoConfig": {
> "source": "-re -i rtsp://myfancy_rtsp_stream",
> "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
> "maxStreams": 2,
> "maxWidth": 1280,
> "maxHeight": 720,
> "maxFPS": 30,
> "vcodec": "h264_omx",
> "audio": true,
> "packetSize": 188,
> "debug": true
> }
> }
> ]
> }

Thank you; that did the trick...I had the parameter in the incorrect portion of the config.  Thank you again!!
