### ISSUE TITLE
video configuration

### ISSUE THREAD

**Issue by UKenGB** [Samfox2/homebridge-videodoorbell#76]
How can I change the streaming config?

When I watch the Live feed from the doorbell, the Homebridge log ALWAYS shows:-

"Start streaming video from Front Door with 1280x720@299kBit"

The doorbell actually outputs 1536x2048, but I've set ffmpeg to scale that to 1280x960 (which it does do) and that runs at at a bitrate of about 366 kbits/s, so I set maxBitrate to 400. So why is it apparently still streaming at 1280x720@299kBit. Whatever settings I have changed in the plug-ins config has actually made no difference. Well, the ffmpeg output is being scaled, but I cannot change what HomeKit actually receives. I could scale it to 1280x720, but why can I not specify what I want it to be when 1280x960 is an acceptable HomeKit size?

**Comment by Samfox2** [comment]
Homekit asks for different resolutions depending on the available bandwidth and/or device. This is an adaptive process and should not be changed.
