### ISSUE TITLE
Option to activate HomePod for ringing ... doesnt work :-(

### ISSUE THREAD

**Issue by roe1974** [Samfox2/homebridge-videodoorbell#78]
as described ... the Homepod-Ring Option is not possible to activate .... "Error"
Is there a workaround ?
br, Richard

**Comment by Samfox2** [comment]
Strange, it is working with my homepod and homepod mini.

**Comment by roe1974** [comment]
thats the error when activating...![Uploading 105891273...]

**Comment by Samfox2** [comment]
You need at least iOS 13.3. If it is still not working, you could try to sign out from icloud and reconnect afterwards.

**Comment by roe1974** [comment]
I use the plugin (currently 0.2.9) for about 1.5 years. Since then the camera is in Homekit. Should I remove it once and add it again?
I also use a second camera with the "homebridge-camera-ffmpeg" plugin (version 1.3.0). Can this interfere ?
iOS was until yesterday 14.3, today 14.4 ... same error.

**Comment by roe1974** [comment]
...also I just noticed that in the settings of my home, in the overview, I get only one camera displayed ... the one from your plugin ... the second camera does not appear here ... normal ?

**Comment by Samfox2** [comment]
Running homebridge-camera-ffmpeg beside should not be the problem. It is still working for me.
You could probably remove the doorbell and add it again, maybe that helps. 
If you do receive the rich message at your phone it seems to be a homekit related problem. If it is still not working you could try to reset your HomePod. It is not a big deal to add it again to your setup. Maybe that solves  your problem.

**Comment by roe1974** [comment]
both tested ... no change :-(
yes, rich message works without any problem !
is there a speciel setting to do in config.json ?
br, Richard

**Comment by toshibochan** [comment]
Show us your config without any user name and password.

**Comment by roe1974** [comment]
here the config of the homebridge camera instance:

{
"bridge": {
    "username": "xx:xx:xx:xx:xx:xx",
    "name": "Homebridge-Camera",
    "pin": "xxx-xx-xxx",
    "port": 51829
    },
    "plugins": [
       "homebridge-camera-ffmpeg",
       "homebridge-videodoorbell",
       "homebridge-config-ui-x"
    ],

"platforms": [
    {
    "platform": "config",
    "name": "Config",
    "scheduledBackupDisable": true,
    "port": 8084,
    "sudo": false,
    "temp": "/sys/class/thermal/thermal_zone0/temp",
    "restart": "sudo systemctl restart homebridge-camera",
    "log": {
       "method": "systemd",
       "service": "homebridge-camera"
       }
    },
    {
    "platform": "Video-doorbell",
    "cameras": [
       {
       "name": "Eingangstuer",
       "port": 5005,
       "manufacturer": "Edimax",
       "model": "IC-6220DC",
       "firmwareRevision": "3.8",
       "videoConfig": {
          "source": "-rtsp_transport tcp -i rtsp://xxx.xxx.xxx.xxx/ipcam_mjpeg.sdp",
          "stillImageSource": "-i http://xxx:xxx@xxx.xxx.xxx.xxx/snapshot.jpg",
          "maxStreams": 2,
          "packetSize": 188,
          "maxWidth": 640,
          "maxHeight": 360,
          "maxFPS": 30,
          "vcodec": "h264_omx"
          }
       }
    ]
    },
    {
    "platform": "Camera-ffmpeg",
    "cameras": [
       {
       "name": "Parkplatz",
       "manufacturer": "Edimax",
       "model": "IC-9110W",
       "firmwareRevision": "3.11",
       "videoConfig": {
          "source": "-rtsp_transport tcp -i rtsp://xxx.xxx.xxx.xxx/ipcam_h264s1.sdp",
          "stillImageSource": "-i http://xxx.xxx@xxx.xxx.xxx.xxx/snapshot.jpg",
          "maxStreams": 2,
          "packetSize": 188,
          "maxWidth": 640,
          "maxHeight": 360,
          "maxFPS": 30,
          "vcodec": "h264_omx"
          }
       }
    ]
    }
    ],

"accessories": [
    ]
}

**Comment by toshibochan** [comment]
Missing  "button": true,

**Comment by roe1974** [comment]
tested, nö change :(

**Comment by toshibochan** [comment]
You have to make automation using this button.

**Comment by Samfox2** [comment]
It is actually working without an automation. All you have to do is enable 'Chime on HomePod' to get the speaker playing the sound if the doorbell rings. Did you already try to enable the option from another device?

**Comment by roe1974** [comment]
this is my only doorbell in HK ...

**Comment by Samfox2** [comment]
Sorry, I meant: ...from another iPad or iPhone?

**Comment by roe1974** [comment]
I have now activated HomeKit on the iPad. There in the settings of the doorbell immediately the ringing on the Homepod has been activated. When I ring the bell, however, it does not work. So I can turn on / off the function on the iPad, but it does not go. On the iPhone, however, it always remained off and can still not be switched on. Very strange.

**Comment by roe1974** [comment]
just came home ... now suddently it works... perhaps it was the trick with the ipad ... great !!!! thx :)

**Comment by Samfox2** [comment]
Nice to hear that it is working now.
