### ISSUE TITLE
Update to 0.3.0 with WARNS .... Ok ?

### ISSUE THREAD

**Issue by roe1974** [Samfox2/homebridge-videodoorbell#79]
I got this WARNs while upgrading to 0.3.0 .... is it Ok ? .. br Richard

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/314                                                  2

added 37 packages, removed 3 packages, changed 71 packages, and audited 109 packages in 13s

4 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

**Comment by Samfox2** [comment]
Yes it is ok, no prob.
