### ISSUE TITLE
Fails to load up camera

### ISSUE THREAD

**Issue by brownad** [Samfox2/homebridge-videodoorbell#8]
Hi,

I'm using the original plugin with no issues, but failing to get the camera to show up:

[1/9/2018, 8:00:11 PM] Loaded plugin: homebridge-videodoorbell
[1/9/2018, 8:00:11 PM] Registering platform 'homebridge-videodoorbell.Video-doorbell'
[1/9/2018, 8:00:11 PM] ---
[1/9/2018, 8:00:11 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/9/2018, 8:00:11 PM] ---
[1/9/2018, 8:00:11 PM] Loading 1 platforms...
[1/9/2018, 8:00:11 PM] [Video-doorbell] Initializing Video-doorbell platform...

Config is valid (copy of my existing camera config plus the port you've added).  Is there any scenario where it can be added but there's no camera?  I created a new Home to test it and load this one in with it to no avail.

**Comment by brownad** [comment]
No difference, it adds homebridge but no camera shown.  I was able to test the curl commands and saw them work in the running terminal..

**Comment by brownad** [comment]
Running on a mac if that makes a difference, also I loaded up ffmpeg

**Comment by Samfox2** [comment]
If ffmpeg plugin is working this should also work. Could you try to change both name and username in your config json and delete persist folder?

**Comment by brownad** [comment]
No difference there either.

Just adds homebridge with nothing under homebridge.

**Comment by Samfox2** [comment]
Just to make it sure, you have to add the camera by yourself, did you do that? It appears after hitting the plus button at the top right in home app and you have to use the same pin as your running homebridge uses.

**Comment by brownad** [comment]
Awesome, been a while since I setup a test rig :( thanks for the basic reminder.

closing the chat.

**Comment by Samfox2** [comment]
Good to hear that it`s working now.
