### ISSUE TITLE
Doorbell dummy switch

### ISSUE THREAD

**Issue by fmpmsilva** [Samfox2/homebridge-videodoorbell#80]
Hi. Is there a away to use only use the doorbell dummy switch without video or stills?
Thanks.

**Comment by Samfox2** [comment]
You can use the switch without configuring a proper video path. You will then receive only a message (without pic). However, an ampty video screen will be visible in home app.

**Comment by fmpmsilva** [comment]
And it’s possible to put an image on the empty screen?

**Comment by Samfox2** [comment]
Sure. You can set the stillimagepath to an image of your choice.

**Comment by fmpmsilva** [comment]
I’m using an iMac. It’s possible to tell me how to do it?

**Comment by Samfox2** [comment]
` "stillImageSource": "-re -i /home/homebridge/test.jpg", `

This is the command (linux) for a pic „test.jpg“ located in home directory of user „homebridge“. Should also work for macOS.

![6C1E1655-5AD0-4739-8CA5-264DDC23F0C2](https://user-images.githubusercontent.com/11883712/110145490-c74cb380-7dd9-11eb-9dfc-f8c8103bb8dc.jpeg)

**Comment by fmpmsilva** [comment]
Thanks for the answer. I could try but I can’t get the plug in to work. Doesn’t ad nothing to my HomeKit.

**Comment by Samfox2** [comment]
You have to add the cam to your home after homebridge is running.

**Comment by fmpmsilva** [comment]
Not showing
