### ISSUE TITLE
Problems with vcodec

### ISSUE THREAD

**Issue by jpleite** [Samfox2/homebridge-videodoorbell#82]
Hi Samfox2. Great plugin and great job. I'm not sure if you can help me. I use homebridge on a Synology DS218 docker container and own a Reolink which I had configured in Homebridge Camera FFmpeg using vcodec": "copy. It was working great. However, when using your plugin I can only use "vcodec": "libx264" which is much slower. Compiled a static ffmpeg version for amd64 and included the path but still is not working. Is there any chance I can use your plugin combined with Homebridge Camera FFmpeg so I can still expose a ding dong but use the much fast Homebridge Camera FFmpeg processor? Trying to figure out a way but could not do it

**Comment by Samfox2** [comment]
Hi jpleite. Not sure why copy should be slower as it only passes the stream through without any re-encoding. However, think homebridge-ffmpeg does now also support a doorbell-trigger via a http request so you could use this as an alternative.

**Comment by jpleite** [comment]
Hi @Samfox2. Thanks for the help. In fact, homebridge-ffmpeg does the job. Thanks for pointing out
